### PR TITLE
fix: Switch to dot constructor in defrecords

### PR DESCRIPTION
**Pull request by KingMob**
Avoids cljs warning about ->ConditionedGPM being undefined

### CODE REVIEW

**Comment by sritchie** [comment]
Can you add a note to the PR about why this imwarning is coming up, maybe a link to the conversation with Thomas?

**Review by sritchie — APPROVED** [review]

**Comment by KingMob** [comment]
Sure. Thomas didn't have much to say, other than that he didn't think it was related to shadow.

## Background

I started getting the following warning in shadow-cljs when trying to load the `inferenceql.inference.gpm.conditioned` ns. Clojure worked ok, and it appears the existing node-based tests at the command-line worked ok as well. There may be some loading order confound, not sure. 

The docs make no promises about the availability of the arrow constructor inside a defrecord form. To be safe, this PR changes the constructor from the arrow form to the dot form, which compiles without warning.

```
------ WARNING #1 - :undeclared-var --------------------------------------------
 File: /Users/matthew/.gitlibs/libs/io.github.inferenceql/inferenceql.inference/40e77dedf680b7936ce988b66186a86f5c4db6a5/src/inferenceql/inference/gpm/conditioned.cljc:21:8
--------------------------------------------------------------------------------
  18 |   gpm.proto/Condition
  19 |   (condition [_ new-conditions]
  20 |     (let [merged-conditions (merge conditions new-conditions)]
  21 |       (->ConditionedGPM gpm merged-conditions))))
--------------^-----------------------------------------------------------------
 Use of undeclared Var inferenceql.inference.gpm.conditioned/->ConditionedGPM
--------------------------------------------------------------------------------
  22 |
  23 | (defn condition
  24 |   "Conditions gpm based on conditions via rejection sampling. Arguments are the
  25 |   same as those for `inferenceql.inference.gom/condition`."
--------------------------------------------------------------------------------
```

**Comment by KingMob** [comment]
Can someone with permissions merge this, and then give me permissions for the future?

**Comment by sritchie** [comment]
Oh I didn't expand out context and see that this was inside that record's definition! Yes this makes sense and this is what I do as well (vs the alternate approach of 

(declare ->....)

Good stuff and thanks for the extra context.

**Comment by KingMob** [comment]
@sritchie Thing is, it works just fine in Clojure, though there's nothing in the docs actually promising that. 

As I wrote on ask.clojure.org:

> I noticed that in the clj defrecord macro, the symbols for ->Foo and map->Foo are declared first thing, but in cljs, the related build-positional-factory and build-map-factory fns are called at the end, after emit-defrecord. Perhaps that's the issue?

Hopefully it will be synchronized between clj and cljs and/or have the docs clarified on this matter.

**Pull request merged**
